---
title: "Présentation"
---

**Extrait du guide pour le comité de pilotage des *Rencontres R* (2012):**

*L’esprit des Rencontres R est de fournir à l’échelle nationale un lieu d’échange et de partage d’idées sur l’usage du logiciel R dans différentes disciplines (Visualisation & graphiques, Statistique appliquée, Biostatistique, Statistique bayésienne, Bioinformatique, Analyse des données, Modélisation, Machine learning, High performance computing...).*

*Ces rencontres sont destinées à tous types d’utilisateurs de R : les chercheurs, les enseignants, les industriels, les étudiants, ... Elles sont ouvertes aux statisticiens, aux informaticiens et à tous les domaines d’application. Elles s'adressent aussi bien aux débutants qu'aux utilisateurs confirmés et expérimentés.*

**Historique**

C'est en août 2011 (juste après la conférence internationale useR! 2011) qu'est née l’idée de créer une version française de ce type de manifestation autour du logiciel R. Les personnes à l’initiative de cet événement sont : Marie Chavent, Robin Genuer, François Husson, Julie Josse, Benoit Liquet, Jérôme Saracco.

Les premières rencontres R ont ainsi été organisées les 2 et 3 juillet 2012 à Bordeaux. Elles ont bénéficié immédiatement du parrainage de la SFdS (Société Française de Statistique), ainsi que celui de la SMAI et de la SFB (Société Française de Biométrie).
